name: Build H5GG Tweak

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install ldid dpkg make
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build tweak
        run: |
          export THEOS=$HOME/theos
          make clean
          make

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: deb-packages
          path: ./packages/
